### ISSUE TITLE
Support laravel-websockets (pusher-compatible)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Notifications#5]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

adding host & port configurations to echo/pusher instances makes it compatible with Laravel-Websockets, a self-hosted pusher alternative that includes a compatible API
[docs](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#requirements)

### Notable changes

add a `host` & `port` option to config/broadcast.php, ex.:
```php
            'options' => [
              'host' => env('PUSHER_APP_HOST', 'api.pusherapp.com'),
              'port' => env('PUSHER_APP_PORT', 6001),
              ...
```
when instantiating an Echo (currently in `IO.vue` & `Notifications.vue`), add a `wsHost` & `wsPort` option. `disableStats` should also be set to true as this would keep sending client-side stats to pusher.
ex.: (extra meta attributes would need to be forwarded)
```js
                wsHost: this.meta.pusherHost,
                wsPort: this.meta.pusherPort,
                disableStats: true,
```

**Comment by jlsjonas** [comment]
We're rolling it out right now, so I can't give full conclusions on it; but it's working great so far.
[According to their blog](https://murze.be/introducing-laravel-websockets-an-easy-to-use-websocket-server-implemented-in-php#does-it-scale) (unless client-side stats are really important to your of course, as those are disabled as per my above comment) you can easily have ~15k connections on the smallest DO _droplet_ (~$5/mo)

The free plan does not accommodate our needs as we'll have 100's of (mostly idle) connections as our locations _log in for the day_.

**Comment by aocneanu** [comment]
Do you intend to make a PR for this?

**Comment by jlsjonas** [comment]
Sorry we had more pressing issues coming up.
I've just rounded up implementing & testing the laravel-websocket implementation so I should be able to PR the changes later this week.

We had some initial hiccups, mostly related to SSL; but _fixed_ them by using a proper production strategy (reverse-proxy); I'll add important notes to the PR code and/or docs.
